// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbGIJa1kBb0VYl1VpP6qGRwlRlUVYu-ug',
    appId: '1:296301960795:web:33ca5024cc8faba4eae97e',
    messagingSenderId: '296301960795',
    projectId: 'auth-f6f91',
    authDomain: 'auth-f6f91.firebaseapp.com',
    storageBucket: 'auth-f6f91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIFhAvKPP-939USoAXElOMbhR_S1-qS7g',
    appId: '1:296301960795:android:8581b9caa28b3a5aeae97e',
    messagingSenderId: '296301960795',
    projectId: 'auth-f6f91',
    storageBucket: 'auth-f6f91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZA25NjdfO5yhOLxsVud7m5Xt7oWSQ5cE',
    appId: '1:296301960795:ios:5907d21cbbd4685ceae97e',
    messagingSenderId: '296301960795',
    projectId: 'auth-f6f91',
    storageBucket: 'auth-f6f91.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZA25NjdfO5yhOLxsVud7m5Xt7oWSQ5cE',
    appId: '1:296301960795:ios:5907d21cbbd4685ceae97e',
    messagingSenderId: '296301960795',
    projectId: 'auth-f6f91',
    storageBucket: 'auth-f6f91.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbGIJa1kBb0VYl1VpP6qGRwlRlUVYu-ug',
    appId: '1:296301960795:web:e6c5d82332b175f8eae97e',
    messagingSenderId: '296301960795',
    projectId: 'auth-f6f91',
    authDomain: 'auth-f6f91.firebaseapp.com',
    storageBucket: 'auth-f6f91.appspot.com',
  );

}